name: binge_prime
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: null
  cupertino_icons: null
  firebase_analytics: null
  firebase_auth: ^0.16.0
  firebase_core: null
  firebase_messaging: null
  google_sign_in: null
  mdi: null
  video_player: null
  cached_network_image:
  cloud_functions: ^0.5.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
